[package]
name = "renderer_vulkan"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
cgmath.workspace = true
log.workspace = true
png.workspace = true
thiserror.workspace = true
tobj.workspace = true
kani_volcano_math = { package = "kani-volcano-math", path = "../kani_volcano_math" }
vulkanalia.workspace = true
winit.workspace = true
